name = "ParallelUtilities"
uuid = "fad6cfc8-4f83-11e9-06cc-151124046ad0"
authors = ["Jishnu Bhattacharya <jishnuonline@gmail.com>"]
version = "0.3.3"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Reexport = "0.2"
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
